/**
 * Clayful
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minsu.lee@dietfriends.co.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Name } from './name';


export interface Address { 
    name?: Name;
    company?: string;
    postcode?: string;
    country: string;
    state?: string;
    city?: string;
    address1: string;
    address2?: string;
    mobile?: string;
    phone?: string;
}

