/**
 * Clayful
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minsu.lee@dietfriends.co.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TImeValue } from './tImeValue';
import { Address } from './address';
import { Image } from './image';
import { Name } from './name';


export interface Customer { 
    _id: string;
    name: Name;
    address?: Address;
    connect: boolean;
    verified: boolean;
    groups?: Array<object>;
    userId: string;
    alias?: string;
    email?: string;
    avatar?: Image;
    gender?: string;
    birthdate?: string;
    country?: string;
    mobile?: string;
    phone?: string;
    language?: string;
    currency?: string;
    timezone?: string;
    deactiveatedAt?: string;
    lastLoggedInAt?: TImeValue;
    meta?: object;
    createdAt?: TImeValue;
    updatedAt?: TImeValue;
}

