/**
 * Clayful
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minsu.lee@dietfriends.co.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateMeRequestAddress } from './updateMeRequestAddress';
import { Name } from './name';


export interface UpdateMeRequest { 
    alias?: string;
    avatar?: string;
    name?: Name;
    address?: UpdateMeRequestAddress;
    mobile?: string;
    phone?: string;
    gender?: string;
    birthdate?: string;
    country?: string;
    language?: string;
    currency?: string;
    timezone?: string;
    meta?: object;
}

