/**
 * Clayful
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: minsu.lee@dietfriends.co.kr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Discount } from './discount';
import { NumberValue } from './numberValue';
import { ProductPrice } from './productPrice';
import { Image } from './image';


export interface Variant { 
    price?: ProductPrice;
    discount?: Discount;
    available?: boolean;
    thumbnail?: Image;
    quantity?: NumberValue;
    sku?: string;
}

