name: sdk

on:
  push:
    #paths:
    #  - 'oas.yaml'
    branches:
      - master
jobs:
  build:
    name: dart sdk
    runs-on: ubuntu-latest

    #container:
    #  image:  google/dart:latest

    if: "! contains(github.event.head_commit.message, '[codegen skip]') && ! contains(github.event.head_commit.message, '[skip codegen]')"

    steps:
      - uses: actions/checkout@v2
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
      - name: gen
        run: |
          setopt +o nomatch
          rm -rf sdk/api
          rm -rf sdk/model
          rm sdk/*.ts
          rm sdk/ng-package.json
          rm sdk/README.md
          rm sdk/tsconfig.json
          generate.sh
      #- name: bump version
      #  run: |
      #    perl -i -pe 's/^(version:\s+)(\d+\.\d+\.\d+\+)(\d+)$/$1.$ENV{API_VERSION}."+".$ENV{GITHUB_RUN_NUMBER}/e' pubspec.yaml
      - name: Git push
        run: |
          git checkout master
          git add .
          git commit -m "Automatic Code Generator" -m "[skip codegen]" || true
          git push origin master
